### ISSUE TITLE
reproduct

### ISSUE THREAD

**Issue by weiheng-liu** [Gutianpei/MID#19]
hello sir
    I reproducted your excellent work "MID", but I found I had a bad result in FDE in every dataset, Can you tell me your spefic training method to help me solve this problem?
![425b961351767caf04e2c7043006f71](https://github.com/Gutianpei/MID/assets/103296010/3765eb5e-fac5-4768-b20f-1bd2ea5a4b3d)

**Comment by packer-c** [comment]
Hi, did you change some parameters before getting these results?

**Comment by Gutianpei** [comment]
Hello @leoliumessi,

We use the same config and training strategy for each dataset. Since your result matched our result in ETH and UNIV, the rest three datasets should work too. However, we do straggle on HOTEL and ZARA1 when we trained model, and retrain it usually helps due to the stochasticity of our work.

**Comment by weiheng-liu** [comment]
> Hello @leoliumessi,
> 
> We use the same config and training strategy for each dataset. Since your result matched our result in ETH and UNIV, the rest three datasets should work too. However, we do straggle on HOTEL and ZARA1 when we trained model, and retrain it usually helps due to the stochasticity of our work.

ok, thank you sir! I will have a try to retrain the model.

**Comment by leoliumessi** [comment]
> 

no , I changed nothing.

**Comment by weiheng-liu** [comment]
> Hi, did you change some parameters before getting these results?

no, I changed nothing.
